# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Closers Flutter

on:
  push:
    branches: [ "main" ]
    paths: [ "domains/client/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "domains/client/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        working-directory: ./domains/client
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        working-directory: ./domains/client
        run: flutter analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      # - name: Run tests
      #   working-directory: ./domains/client
      #   run: flutter test

      # - name: Upload to dropbox
      #   uses: aTable/deploy-to-dropbox@v1.0.7
      #   with:
      #     DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESSTOKEN }}
      #     DROPBOX_DESTINATION_PATH_PREFIX: "/GithubActionsUploader/"
      #     GLOB: "domains/client/pubspec.yaml"

      - name: Upload to Dropbox
        uses: Lewuathe/dropbox-github-action@v1
        with:
          dropbox-app-key: ${{ secrets.DROPBOX_APPKEY }}
          dropbox-app-secret: ${{ secrets.DROPBOX_APPSECRET }}
          dropbox-refresh-token: ${{ secrets.DROPBOX_ACCESSTOKEN }}
          source-path: "domains/client/pubspec.yaml"
          target-path: "/GithubActionsUploader/test.yaml"
